export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FETCH_BLOGS = 'FETCH_BLOGS';
export const FETCH_BLOGS_ERROR = 'FETCH_BLOGS_ERROR';